[package]
name = "santpersantper/alba-website"
version = "0.1.0"
description = "Alba website static files"
private = true

[dependencies]
"wasmer/static-web-server" = "*"

[[command]]
name = "server"
module = "wasmer/static-web-server:server"
runner = "https://webc.org/runner/wasi/command/0.0.1"

[command.annotations.wasi]
env = [
  "SERVER_LISTEN_ADDR=[::]:8080",
  "SERVER_PAGE_FALLBACK=./index.html",
]
